#language: node_js
#node_js:
#  - 'lts/*'
#cache:
#  directories:
#    - node_modules
#branches:
#  only:
#    - dev
#script:
#  - echo 'Installing dependencies'
#  - yarn
#  - echo 'Running unit tests'
#  - yarn test
services:
  - docker

before_install:
  - make test

