version: "3.7"
services:
  app-api:
    container_name: takehome-assignment-app-api
    build:
      context: ../
      dockerfile: ./docker/api.Dockerfile
    volumes:
      - '.:/app/'
      - '/app/node_modules'
    ports:
      - 3001:3001
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
