version: '3.7'
services:
  gamereview-api:
    container_name: gamereview-api
    image: jangroy91/gamereview-api:latest
    ports:
      - 3001:3001
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
